import SwiftUI
import AVFoundation

let textsByLanguage: [String: [(text: LocalizedStringKey, duration: TimeInterval)]] = [
    "en": [
        ("Take a moment to feel the connection with your body and your breath.", 8),
        ("Let the air gently flow in and expand where it is needed.", 7),
        ("Give yourself the time to listen to what your body is communicating today.", 8),
        ("Gently bring your attention to the part of you that feels good right now, even if it’s just a small area of comfort.", 12),
        ("If it feels right, you can accompany this sensation with a light touch, as if giving yourself a gentle hug.", 12),
        ("Let the warmth of your hand bring support and security, like an act of care towards yourself.", 9),
        ("Stay in this feeling of well-being for a moment, allowing it to expand like a gentle light within you.", 10),
        ("Allow yourself to enjoy this space of calm, knowing that you can always return to it whenever you need.", 11),
        ("If it feels right, try gently shifting your attention to another part of your body, perhaps one you haven’t considered yet.", 13),
        ("Wherever this experience takes you, you are safe. You are welcomed exactly as you are.", 12),
        ("Your body has its own wisdom, knowing how to find balance between what feels light and what feels intense.", 11),
        ("Now, without forcing anything, notice if there is a part that feels tense, tired, or heavy.", 12),
        ("If you’d like, try bringing your hand to that area with kindness, without judging the sensation.", 9),
        ("Imagine offering that area the same warmth and care you would give to someone you love.", 8),
        ("There is nothing to change or fix right away—simply stay present with your touch and your breath.", 9),
        ("Take a moment to feel the difference between before and now, without expectations.", 8),
        ("Thank your body for welcoming this experience, exactly as it could today.", 8),
        ("When you’re ready, slowly let go of the contact and return your awareness to the space around you.", 15)
    ],
    "it": [
        ("Prenditi un momento per sentire il contatto con il tuo corpo e il tuo respiro.", 8),
        ("Lascia che l’aria entri dolcemente e si espanda dove serve.", 7),
        ("Concediti il tempo di ascoltare cosa il tuo corpo ti comunica oggi.", 8),
        ("Porta dolcemente l’attenzione su quella parte di te che in questo momento si sente bene, anche solo un piccolo angolo di comfort.", 12),
        ("Se ti fa piacere, puoi accompagnare questa sensazione con un tocco leggero, come fosse un abbraccio gentile a te stesso.", 12),
        ("Lascia che il calore della tua mano porti sostegno e sicurezza, come un gesto di cura verso di te.", 9),
        ("Rimani un momento in questa sensazione di benessere, lasciandola espandere come una luce gentile dentro di te.", 12),
        ("Concediti di godere di questo spazio di calma, sapendo che puoi sempre tornarci quando ne hai bisogno.", 10),
        ("Se ti fa piacere, prova a spostare dolcemente l’attenzione verso un’altra zona del corpo, magari una che finora non hai considerato.", 12),
        ("Ovunque ti porti questa esperienza, sei al sicuro. Sei accolto esattamente così come sei.", 10),
        ("Il tuo corpo ha una sua saggezza, sa trovare equilibrio tra ciò che è leggero e ciò che è più intenso.", 10),
        ("Ora, senza forzare, nota se c’è una parte che si sente più tesa, stanca o appesantita.", 8),
        ("Se ti va, prova ad avvicinare una mano con gentilezza, senza giudicare quella sensazione.", 8),
        ("Immagina di poter offrire a quella zona la stessa cura e calore che daresti a qualcuno a cui vuoi bene.", 8),
        ("Non c’è nulla da cambiare o risolvere subito, semplicemente rimani presente con il tuo tocco e il tuo respiro.", 10),
        ("Prenditi un momento per sentire la differenza tra prima e ora, senza aspettative.", 7),
        ("Ringrazia il tuo corpo per aver accolto questa esperienza, esattamente come poteva oggi.", 7),
        ("Quando sei pronto, lascia andare il contatto lentamente e torna a sentire l’ambiente intorno a te.", 15)
    ],
    "fr": [
        ("Prends un moment pour te connecter à ton corps et à ta respiration.", 8),
        ("Laisse l’air circuler doucement et se déployer là où c’est nécessaire, sans effort.", 8),
        ("Accorde-toi le temps d’écouter ce que ton corps a à te dire aujourd’hui.", 7),
        ("Dirige doucement ton attention vers la partie de toi qui se sent bien en ce moment, même si ce n’est qu’une petite zone de confort.", 9),
        ("Si cela te semble juste, tu peux accompagner cette sensation d’un geste doux, comme si tu t’offrais une étreinte bienveillante.", 12),
        ("Laisse la chaleur de ta main apporter soutien et réconfort, comme un acte de soin envers toi-même.", 9),
        ("Reste un instant dans cette sensation de bien-être, en la laissant se diffuser comme une lumière douce à l’intérieur de toi.", 10),
        ("Permets-toi de savourer cet espace de calme, en sachant que tu peux toujours y revenir quand tu en as besoin.", 9),
        ("Si tu en ressens l’envie, essaie de déplacer doucement ton attention vers une autre partie de ton corps, peut-être une que tu n’as pas encore explorée.", 12),
        ("Où que cette expérience te mène, tu es en sécurité. Tu es accueilli(e) tel(le) que tu es.", 10),
        ("Ton corps possède sa propre sagesse et sait naturellement trouver l’équilibre entre ce qui est léger et ce qui est intense.", 9),
        ("Sans rien forcer, remarque s’il y a une partie de toi qui se sent tendue, fatiguée ou lourde.", 9),
        ("Si tu le souhaites, pose ta main sur cette zone avec bienveillance, sans juger la sensation.", 9),
        ("Imagine offrir à cette zone la même chaleur et la même tendresse que tu donnerais à quelqu’un que tu aimes.", 8),
        ("Il n’y a rien à changer ou à réparer tout de suite ; sois simplement présent(e) avec ton toucher et ta respiration.", 11),
        ("Prends un moment pour ressentir la différence entre avant et maintenant, sans attentes.", 9),
        ("Remercie ton corps d’avoir accueilli cette expérience, tel qu’il est aujourd’hui.", 7),
        ("Lorsque tu te sens prêt(e), relâche doucement le contact et ramène ton attention à l’espace qui t’entoure.", 11)
    ],
    "es-419": [
        ("Tómate un momento para sentir la conexión con tu cuerpo y tu respiración.", 7),
        ("Deja que el aire fluya suavemente y se expanda donde sea necesario.", 7),
        ("Dáte el tiempo para escuchar lo que tu cuerpo te está comunicando hoy.", 7),
        ("Dirige suavemente tu atención hacia la parte de ti que se siente bien en este momento, aunque solo sea una pequeña zona de confort.", 10),
        ("Si se siente bien, puedes acompañar esta sensación con un toque suave, como si te estuvieras dando un abrazo gentil.", 9),
        ("Deja que el calor de tu mano brinde apoyo y seguridad, como un acto de cuidado hacia ti mismo.", 7),
        ("Permaneces en esta sensación de bienestar por un momento, permitiendo que se expanda como una luz suave dentro de ti.", 9),
        ("Permítete disfrutar de este espacio de calma, sabiendo que siempre puedes regresar a él cuando lo necesites.", 9),
        ("Si se siente bien, intenta mover suavemente tu atención hacia otra parte de tu cuerpo, quizás una que aún no has considerado.", 10),
        ("Dondequiera que te lleve esta experiencia, estás a salvo. Eres bienvenido tal como eres.", 8),
        ("Tu cuerpo tiene su propia sabiduría, sabiendo cómo encontrar el equilibrio entre lo que se siente ligero y lo que se siente intenso.", 10),
        ("Ahora, sin forzar nada, nota si hay alguna parte que se siente tensa, cansada o pesada.", 8),
        ("Si lo deseas, intenta llevar tu mano a esa área con amabilidad, sin juzgar la sensación.", 8),
        ("Imagina ofrecerle a esa área la misma calidez y cuidado que le darías a alguien que amas.", 7),
        ("No hay nada que cambiar o arreglar de inmediato; simplemente permanece presente con tu toque y tu respiración.", 9),
        ("Tómate un momento para sentir la diferencia entre antes y ahora, sin expectativas.", 7),
        ("Agradece a tu cuerpo por acoger esta experiencia, tal como pudo ser hoy.", 7),
        ("Cuando estés listo, suelta lentamente el contacto y devuelve tu conciencia al espacio que te rodea.", 9)
    ]
]

